// flow-typed signature: 995596e7a06251638c696922a546245b
// flow-typed version: <<STUB>>/cash-dom_v^1.3.5/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cash-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cash-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cash-dom/dist/cash' {
  declare module.exports: any;
}

declare module 'cash-dom/dist/cash.min' {
  declare module.exports: any;
}

declare module 'cash-dom/gulpfile' {
  declare module.exports: any;
}

declare module 'cash-dom/src/_wrapper' {
  declare module.exports: any;
}

declare module 'cash-dom/src/attributes' {
  declare module.exports: any;
}

declare module 'cash-dom/src/collection' {
  declare module.exports: any;
}

declare module 'cash-dom/src/core' {
  declare module.exports: any;
}

declare module 'cash-dom/src/css' {
  declare module.exports: any;
}

declare module 'cash-dom/src/data' {
  declare module.exports: any;
}

declare module 'cash-dom/src/dimensions' {
  declare module.exports: any;
}

declare module 'cash-dom/src/events' {
  declare module.exports: any;
}

declare module 'cash-dom/src/forms' {
  declare module.exports: any;
}

declare module 'cash-dom/src/manipulation' {
  declare module.exports: any;
}

declare module 'cash-dom/src/offset' {
  declare module.exports: any;
}

declare module 'cash-dom/src/traversal' {
  declare module.exports: any;
}

declare module 'cash-dom/src/util' {
  declare module.exports: any;
}

declare module 'cash-dom/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cash-dom/dist/cash.js' {
  declare module.exports: $Exports<'cash-dom/dist/cash'>;
}
declare module 'cash-dom/dist/cash.min.js' {
  declare module.exports: $Exports<'cash-dom/dist/cash.min'>;
}
declare module 'cash-dom/gulpfile.js' {
  declare module.exports: $Exports<'cash-dom/gulpfile'>;
}
declare module 'cash-dom/src/_wrapper.js' {
  declare module.exports: $Exports<'cash-dom/src/_wrapper'>;
}
declare module 'cash-dom/src/attributes.js' {
  declare module.exports: $Exports<'cash-dom/src/attributes'>;
}
declare module 'cash-dom/src/collection.js' {
  declare module.exports: $Exports<'cash-dom/src/collection'>;
}
declare module 'cash-dom/src/core.js' {
  declare module.exports: $Exports<'cash-dom/src/core'>;
}
declare module 'cash-dom/src/css.js' {
  declare module.exports: $Exports<'cash-dom/src/css'>;
}
declare module 'cash-dom/src/data.js' {
  declare module.exports: $Exports<'cash-dom/src/data'>;
}
declare module 'cash-dom/src/dimensions.js' {
  declare module.exports: $Exports<'cash-dom/src/dimensions'>;
}
declare module 'cash-dom/src/events.js' {
  declare module.exports: $Exports<'cash-dom/src/events'>;
}
declare module 'cash-dom/src/forms.js' {
  declare module.exports: $Exports<'cash-dom/src/forms'>;
}
declare module 'cash-dom/src/manipulation.js' {
  declare module.exports: $Exports<'cash-dom/src/manipulation'>;
}
declare module 'cash-dom/src/offset.js' {
  declare module.exports: $Exports<'cash-dom/src/offset'>;
}
declare module 'cash-dom/src/traversal.js' {
  declare module.exports: $Exports<'cash-dom/src/traversal'>;
}
declare module 'cash-dom/src/util.js' {
  declare module.exports: $Exports<'cash-dom/src/util'>;
}
declare module 'cash-dom/test/test.js' {
  declare module.exports: $Exports<'cash-dom/test/test'>;
}
