// flow-typed signature: ce3a4af7a709dce0972047a0117ce36a
// flow-typed version: <<STUB>>/react-transport_v0.0.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transport/lib/index' {
  declare module.exports: any;
}

declare module 'react-transport/lib/transport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transport/lib/index.js' {
  declare module.exports: $Exports<'react-transport/lib/index'>;
}
declare module 'react-transport/lib/transport.js' {
  declare module.exports: $Exports<'react-transport/lib/transport'>;
}
