// flow-typed signature: 521912251762b2e4fae06ed6d9cdbae5
// flow-typed version: <<STUB>>/zip-dir_v^1.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zip-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'zip-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zip-dir/test/zip-dir.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zip-dir/index' {
  declare module.exports: $Exports<'zip-dir'>;
}
declare module 'zip-dir/index.js' {
  declare module.exports: $Exports<'zip-dir'>;
}
declare module 'zip-dir/test/zip-dir.test.js' {
  declare module.exports: $Exports<'zip-dir/test/zip-dir.test'>;
}
